In [1]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[2,3,1],[5,6,4],[9,8,7]])

In [2]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y

array([[2, 3, 1],
       [5, 6, 4],
       [9, 8, 7]])

In [4]:
z=x+y
z

array([[ 3,  5,  4],
       [ 9, 11, 10],
       [16, 16, 16]])

In [5]:
pdot=np.dot(x,y)

In [6]:
pdot

array([[ 39,  39,  30],
       [ 87,  90,  66],
       [135, 141, 102]])

Exercise  :
change in error and 