In [5]:
import pandas as pd
import numpy as np
weight1=1
weight=1
bias=-1

In [6]:
test_inputs=[(0,0),(0,1),(1,0),(1,1)]
correct_outputs=[False,False,False,True]
outputs=[]

In [7]:
for test_inputs,correct_output in  zip(test_inputs,correct_outputs):
    linear_combination=weight1*test_inputs[0]+weight2*test_inputs[1]+bias
    output=int(linear_combination>0)
    is_correct_string="Yes" if output==correct_output else "No"
    outputs.append([test_inputs[0],test_inputs[1],linear_combination,outputs,is_correct_string])
#print output
num_wrong=len([output[4] for output in outputs if output[4]=='No'])
output_frame=pd.DataFrame(outputs,columns=['input 1','input 2','Linear combination','Activation output','Is Correct'])
if not num_wrong:
    print('Nice You got it all correct.\n')
else:
    print('You got {} wrong. keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))
    

NameError: name 'weight2' is not defined

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# set random  seed
np.random.seed(42)

In [10]:
x=np.array([[1,0,0,0],[1,0,1,1],[0,1,0,1]])
print("input:\n",x)
print("\nshape of input:",x.shape)

input:
 [[1 0 0 0]
 [1 0 1 1]
 [0 1 0 1]]

shape of input: (3, 4)


In [11]:
#converting the input in matrix form
x=x.T
print("input in matrix form :\n",x)

print("\nshape of input matrix:" ,x.shape)

input in matrix form :
 [[1 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]

shape of input matrix: (4, 3)


In [12]:
y=np.array([[1],[1],[0]]) # cretaing output array
print("Actual output:\n",y)

y=y.T
print("\nshape of output :",y.shape)


Actual output:
 [[1]
 [1]
 [0]]

shape of output : (1, 3)


In [13]:
inputLayer_neurons=x.shape[0]
hiddenLayer_neurons=3
outputLayer_neurons=1

In [14]:
# initializing weight
#shape os weights_input_hidden should number of neuons at input layer* number of neurons at hidden layer
weights_input_hidden=np.random.uniform(size=(inputLayer_neurons,hiddenLayer_neurons,outputLayer_neurons))

# shape of weights-hidden_output should number of neurons at hidden layer*number of neurons at output layer
weights_hidden_output=np.random.uniform(size=(hiddenLayer_neurons,outputLayer_neurons))

In [15]:
weights_input_hidden.shape,weights_hidden_output.shape # shape of weight matrix

((4, 3, 1), (3, 1))

In [16]:
weights_input_hidden #W...K*M...k inputs..M..neurons

array([[[0.37454012],
        [0.95071431],
        [0.73199394]],

       [[0.59865848],
        [0.15601864],
        [0.15599452]],

       [[0.05808361],
        [0.86617615],
        [0.60111501]],

       [[0.70807258],
        [0.02058449],
        [0.96990985]]])

In [18]:
weights_hidden_output.size  #

3

In [81]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [85]:
hiddenLayer_linearTransform=np.dot(weights_input_hidden.T,x)
hiddenLayer_activations=sigmoid(hiddenLayer_linearTransform)

In [86]:
#Calculating the output 
outputLayer_linearTransform=np.dot(weights_hidden_output.T,hiddenLayer_activations)
output=sigmoid(outputLayer_linearTransform)

In [87]:
#output
output

array([[[0.68334694, 0.72697078, 0.71257368]]])

In [88]:
#calculating the error
error=np.square(y-output)/2
error

array([[[0.05013458, 0.03727248, 0.25388062]]])